### PR TITLE
pywps4.0 demo with py3

### PR DESCRIPTION
**Pull request by jorgejesus**
New pywps4-demo with py3 and binding to 0.0.0.0  The current example of pywps is not working properly, please test this one and replace it

### CODE REVIEW

**Comment by nuest** [comment]
Just to be clear, by current example you mean the pywps 2 one at https://github.com/geocontainers/dockerfiles/blob/master/pycsw/2/Dockerfile

I guess that's outdated anyway!

**Comment by nuest** [comment]
My bad, just saw we have one for 4 too.

**Comment by nuest** [comment]
@jorgejesus Thanks for the PR, the new image works for me.

Would you be so kind to simply replay the Dockerfile in `pywps/4/pywps-demo`, as I don't see a reason to keep this separate just for a different Python version. IMHO the reason for the container is to not let the user worry about which Python is running :-)

Additions to `pywps/3/pywps-demo/README.md ` also welcome, of course.

I'll update the image on Docker Hub asap after the merge.

**Comment by jorgejesus** [comment]
Dear Daniel
I will make the changes generic pywps/4/pywps-demo and commit there. I will open an issue concerning README.md from pywps3

**Comment by jorgejesus** [comment]
Better to close and make a new commit and pull request

**Pull request closed without merging**
