### PR TITLE
[WIP] - Refactor pycsw container

### PR DESCRIPTION
**Pull request by ricardogsilva**
This PR relates to issue #11 

It provides another take on the `pycsw` image featuring:

- Based on python:2.7-alpine
- Fetches pycsw version 2.0.2 in order to ensure reproducible environments
- Installs dependencies for enabling `postgresql` repository backends
- Some documentation on how to use the image

### CODE REVIEW

**Comment by nuest** [comment]
I like sticking to a fixed version, and the docs are very helpful. Thanks!

@ricardogsilva What about adding a [build hook to this to add a `2.0.2` tag](http://windsock.io/automated-docker-image-builds-with-multiple-tags/)?

**Comment by ricardogsilva** [comment]
@nuest sounds good. I'll look into it and update the PR - setting it as WIP for now

**Comment by nuest** [comment]
Great. This is how I got it working for a nodejs webservice: https://github.com/o2r-project/o2r-muncher/blob/master/hooks/post_push (hope it helps!)

**Comment by ricardogsilva** [comment]
@nuest I've been looking at the build hooks docs and at the examples you mentioned (the first one seems to be dead btw) and I'm wondering how to actually implement this and if it is worth it here.

If the Dockerfile was on pycsw's github repo it would be logical to implement a push hook that would tag the built image with the version specified in the repository's branch and have automated docker builds for each version. However here we are dealing with another situation. Since this repository (geocontainers/dockerfiles) features dockerfiles for multiple packages, how do envision coping with successive releases of single packages?

What would be the geocontainers strategy for when pycsw releases next version? 

- Update the offered docker image to the newer version?
- Offer docker images for all subsequent versions?

I'm thinking that perhaps an automated hook for specifying the docker tag may be unneccessary. What's your opinion on this?

**Comment by ricardogsilva** [comment]
@nuest  I'm closing this PR since it does not make much sense anymore IMHO.

We've since added an official docker image to pycsw, featuring automated builds on the [geopython dockerhub repo](https://hub.docker.com/r/geopython/pycsw/).

**Pull request closed without merging**
